version: "3.0"

services:
  mock-service:
    image: nicopozo/mock-service
    container_name: mock-service
    environment:
      - MOCKS_DATASOURCE=file
      - MOCKS_FILE=/tmp/mocks.json
    ports:
      - '8080:8080'
    volumes:
      - /tmp:/tmp