version: "2"
run:
  go: "1.19"
linters:
  default: none
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - cyclop
    - decorder
    - dogsled
    - dupl
    - durationcheck
    - err113
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - forbidigo
    - forcetypeassert
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - goheader
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - govet
    - grouper
    - importas
    - ineffassign
    - lll
    - maintidx
    - makezero
    - misspell
    - mnd
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - nlreturn
    - noctx
    - nolintlint
    - nonamedreturns
    - nosprintfhostport
    - prealloc
    - predeclared
    - promlinter
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - tagliatelle
    - testpackage
    - thelper
    - tparallel
    - unconvert
    - unparam
    - unused
    - varnamelen
    - wastedassign
    - whitespace
    - wrapcheck
    - wsl_v5
  settings:
    tagliatelle:
      case:
        rules:
          json: snake
          xml: snake
          yaml: snake
        use-field-name: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - containedctx
          - err113
          - funlen
          - lll
          - maintidx
          - nosnakecase
          - paralleltest
          - tparallel
          - varnamelen
        path: _test\.go
      - linters:
          - lll
        source: '^//go:generate '
    paths:
      - third_party$
      - builtin$
      - examples$
      - internal/utils/test/mocks
      - ".*\\.my\\.go$"
      - lib/bad.go
      - web/node_modules
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
      - internal/utils/test/mocks
      - ".*\\.my\\.go$"
      - lib/bad.go
      - web/node_modules
