// Code generated by MockGen. DO NOT EDIT.
// Source: ./rule_service.go
//
// Generated by this command:
//
//	mockgen -destination=../utils/test/mocks/rule_service_mock.go -package=mocks -source=./rule_service.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	model "github.com/nicopozo/mockserver/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockRuleService is a mock of RuleService interface.
type MockRuleService struct {
	ctrl     *gomock.Controller
	recorder *MockRuleServiceMockRecorder
	isgomock struct{}
}

// MockRuleServiceMockRecorder is the mock recorder for MockRuleService.
type MockRuleServiceMockRecorder struct {
	mock *MockRuleService
}

// NewMockRuleService creates a new mock instance.
func NewMockRuleService(ctrl *gomock.Controller) *MockRuleService {
	mock := &MockRuleService{ctrl: ctrl}
	mock.recorder = &MockRuleServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRuleService) EXPECT() *MockRuleServiceMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockRuleService) Delete(ctx context.Context, key string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, key)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockRuleServiceMockRecorder) Delete(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockRuleService)(nil).Delete), ctx, key)
}

// Get mocks base method.
func (m *MockRuleService) Get(ctx context.Context, key string) (model.Rule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, key)
	ret0, _ := ret[0].(model.Rule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockRuleServiceMockRecorder) Get(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockRuleService)(nil).Get), ctx, key)
}

// Save mocks base method.
func (m *MockRuleService) Save(ctx context.Context, rule model.Rule) (model.Rule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, rule)
	ret0, _ := ret[0].(model.Rule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Save indicates an expected call of Save.
func (mr *MockRuleServiceMockRecorder) Save(ctx, rule any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockRuleService)(nil).Save), ctx, rule)
}

// Search mocks base method.
func (m *MockRuleService) Search(ctx context.Context, params map[string]any, paging model.Paging) (model.RuleList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Search", ctx, params, paging)
	ret0, _ := ret[0].(model.RuleList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Search indicates an expected call of Search.
func (mr *MockRuleServiceMockRecorder) Search(ctx, params, paging any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Search", reflect.TypeOf((*MockRuleService)(nil).Search), ctx, params, paging)
}

// SearchByMethodAndPath mocks base method.
func (m *MockRuleService) SearchByMethodAndPath(ctx context.Context, method, path string) (model.Rule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchByMethodAndPath", ctx, method, path)
	ret0, _ := ret[0].(model.Rule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchByMethodAndPath indicates an expected call of SearchByMethodAndPath.
func (mr *MockRuleServiceMockRecorder) SearchByMethodAndPath(ctx, method, path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchByMethodAndPath", reflect.TypeOf((*MockRuleService)(nil).SearchByMethodAndPath), ctx, method, path)
}

// Update mocks base method.
func (m *MockRuleService) Update(ctx context.Context, key string, rule model.Rule) (model.Rule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, key, rule)
	ret0, _ := ret[0].(model.Rule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockRuleServiceMockRecorder) Update(ctx, key, rule any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockRuleService)(nil).Update), ctx, key, rule)
}

// UpdateStatus mocks base method.
func (m *MockRuleService) UpdateStatus(ctx context.Context, key string, rule model.RuleStatus) (model.Rule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", ctx, key, rule)
	ret0, _ := ret[0].(model.Rule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockRuleServiceMockRecorder) UpdateStatus(ctx, key, rule any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockRuleService)(nil).UpdateStatus), ctx, key, rule)
}
