// Code generated by MockGen. DO NOT EDIT.
// Source: ./rule_repository.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	gomock "github.com/golang/mock/gomock"
	model "github.com/nicopozo/mockserver/internal/model"
	reflect "reflect"
)

// MockIRuleRepository is a mock of IRuleRepository interface
type MockIRuleRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIRuleRepositoryMockRecorder
}

// MockIRuleRepositoryMockRecorder is the mock recorder for MockIRuleRepository
type MockIRuleRepositoryMockRecorder struct {
	mock *MockIRuleRepository
}

// NewMockIRuleRepository creates a new mock instance
func NewMockIRuleRepository(ctrl *gomock.Controller) *MockIRuleRepository {
	mock := &MockIRuleRepository{ctrl: ctrl}
	mock.recorder = &MockIRuleRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockIRuleRepository) EXPECT() *MockIRuleRepositoryMockRecorder {
	return m.recorder
}

// Save mocks base method
func (m *MockIRuleRepository) Save(ctx context.Context, rule *model.Rule, isUpdate bool) (*model.Rule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, rule, isUpdate)
	ret0, _ := ret[0].(*model.Rule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Save indicates an expected call of Save
func (mr *MockIRuleRepositoryMockRecorder) Save(ctx, rule, isUpdate interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockIRuleRepository)(nil).Save), ctx, rule, isUpdate)
}

// Get mocks base method
func (m *MockIRuleRepository) Get(ctx context.Context, key string) (*model.Rule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, key)
	ret0, _ := ret[0].(*model.Rule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get
func (mr *MockIRuleRepositoryMockRecorder) Get(ctx, key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockIRuleRepository)(nil).Get), ctx, key)
}

// Search mocks base method
func (m *MockIRuleRepository) Search(ctx context.Context, params map[string]interface{}, paging model.Paging) (*model.RuleList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Search", ctx, params, paging)
	ret0, _ := ret[0].(*model.RuleList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Search indicates an expected call of Search
func (mr *MockIRuleRepositoryMockRecorder) Search(ctx, params, paging interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Search", reflect.TypeOf((*MockIRuleRepository)(nil).Search), ctx, params, paging)
}

// SearchByMethodAndPath mocks base method
func (m *MockIRuleRepository) SearchByMethodAndPath(ctx context.Context, method, path string) (*model.Rule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchByMethodAndPath", ctx, method, path)
	ret0, _ := ret[0].(*model.Rule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchByMethodAndPath indicates an expected call of SearchByMethodAndPath
func (mr *MockIRuleRepositoryMockRecorder) SearchByMethodAndPath(ctx, method, path interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchByMethodAndPath", reflect.TypeOf((*MockIRuleRepository)(nil).SearchByMethodAndPath), ctx, method, path)
}

// Delete mocks base method
func (m *MockIRuleRepository) Delete(ctx context.Context, key string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, key)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete
func (mr *MockIRuleRepositoryMockRecorder) Delete(ctx, key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockIRuleRepository)(nil).Delete), ctx, key)
}
